import { Request, Response } from "express";
import { BaseController } from "@/core/BaseController";
import { CartService } from "./cart.service";
import { HTTPStatusCode } from "@/types/HTTPStatusCode";
import { RequestWithUser } from "@/middleware/auth";

export class CartController extends BaseController {
  constructor(private cartService: CartService) {
    super();
  }

  /**
   * GET /api/cart
   * Works for both guest and authenticated users.
   *
   * Authenticated:  Authorization: Bearer <token>
   * Guest:          GET /api/cart?guestCartId=<uuid>
   */
  public getCart = async (req: RequestWithUser, res: Response) => {
    const userId = this.getUserId(req);
    const guestCartId = req.query.guestCartId as string | undefined;

    const cart = await this.cartService.getCart(userId, guestCartId);

    return this.sendResponse(
      res,
      "Cart retrieved successfully",
      HTTPStatusCode.OK,
      cart,
    );
  };

  /**
   * GET /api/cart/count
   * Returns { count: N } — used for cart badge in header.
   *
   * Authenticated:  Authorization: Bearer <token>
   * Guest:          GET /api/cart/count?guestCartId=<uuid>
   */
  public getCartCount = async (req: RequestWithUser, res: Response) => {
    const userId = this.getUserId(req);
    const guestCartId = req.query.guestCartId as string | undefined;

    const result = await this.cartService.getCartCount(userId, guestCartId);

    return this.sendResponse(
      res,
      "Cart count retrieved",
      HTTPStatusCode.OK,
      result,
    );
  };

  /**
   * POST /api/cart/items
   * Body: { productId, quantity?, guestCartId? }
   *
   * Authenticated user → guestCartId is ignored (userId used).
   * Guest → must send guestCartId (UUID generated by frontend).
   */
  public addToCart = async (req: RequestWithUser, res: Response) => {
    const userId = this.getUserId(req);
    const body = req.validatedBody || req.body;

    this.logAction("addToCart", req, {
      productId: body.productId,
      isGuest: !userId,
    });

    const cart = await this.cartService.addToCart(body, userId);

    return this.sendResponse(
      res,
      "Item added to cart",
      HTTPStatusCode.OK,
      cart,
    );
  };

  /**
   * PATCH /api/cart/items/:productId
   * Body: { quantity, guestCartId? }
   */
  public updateQuantity = async (req: RequestWithUser, res: Response) => {
    const userId = this.getUserId(req);
    const { productId } = req.validatedParams || req.params;
    const body = req.validatedBody || req.body;

    this.logAction("updateCartQuantity", req, { productId, isGuest: !userId });

    const cart = await this.cartService.updateQuantity(productId, body, userId);

    return this.sendResponse(
      res,
      "Cart updated successfully",
      HTTPStatusCode.OK,
      cart,
    );
  };

  /**
   * DELETE /api/cart/items/:productId
   * Body: { guestCartId? }
   */
  public removeFromCart = async (req: RequestWithUser, res: Response) => {
    const userId = this.getUserId(req);
    const { productId } = req.validatedParams || req.params;
    const body = req.validatedBody || req.body;

    this.logAction("removeFromCart", req, { productId, isGuest: !userId });

    const cart = await this.cartService.removeFromCart(productId, body, userId);

    return this.sendResponse(
      res,
      "Item removed from cart",
      HTTPStatusCode.OK,
      cart,
    );
  };

  /**
   * DELETE /api/cart
   * Authenticated:  clears user cart
   * Guest:          DELETE /api/cart?guestCartId=<uuid>
   */
  public clearCart = async (req: RequestWithUser, res: Response) => {
    const userId = this.getUserId(req);
    const guestCartId = req.query.guestCartId as string | undefined;

    this.logAction("clearCart", req, { isGuest: !userId });

    const result = await this.cartService.clearCart(userId, guestCartId);

    return this.sendResponse(res, result.message, HTTPStatusCode.OK, result);
  };

  /**
   * POST /api/cart/merge
   * Called immediately after login to merge guest cart → user cart.
   * Body: { guestCartId }
   * Requires: Authentication
   */
  public mergeCart = async (req: RequestWithUser, res: Response) => {
    const userId = this.getUserId(req)!;
    const body = req.validatedBody || req.body;

    this.logAction("mergeCart", req, { userId, guestCartId: body.guestCartId });

    const cart = await this.cartService.mergeGuestCart(userId, body);

    return this.sendResponse(
      res,
      "Cart merged successfully",
      HTTPStatusCode.OK,
      cart,
    );
  };
}
