import { z } from "zod";

export const CartValidation = {
  /**
   * POST /api/cart/items
   * Add item to cart — works for both guest and authenticated users
   */
  addItem: z
    .object({
      productId: z.string().uuid("Product ID must be a valid UUID"),
      quantity: z
        .number()
        .int()
        .min(1, "Quantity must be at least 1")
        .max(100, "Quantity cannot exceed 100")
        .default(1),
      // Guest cart session ID (generated by frontend, stored in localStorage)
      guestCartId: z
        .string()
        .uuid("Guest cart ID must be a valid UUID")
        .optional(),
    })
    .strict(),

  /**
   * PATCH /api/cart/items/:productId
   * Update quantity — works for both guest and authenticated users
   */
  updateQuantity: z
    .object({
      quantity: z
        .number()
        .int()
        .min(1, "Quantity must be at least 1")
        .max(100, "Quantity cannot exceed 100"),
      guestCartId: z.string().uuid().optional(),
    })
    .strict(),

  /**
   * DELETE /api/cart/items/:productId
   */
  removeItem: z
    .object({
      guestCartId: z.string().uuid().optional(),
    })
    .strict(),

  /**
   * POST /api/cart/merge
   * After login — merge guest cart into user cart
   */
  mergeCart: z
    .object({
      guestCartId: z.string().uuid("Guest cart ID must be a valid UUID"),
    })
    .strict(),

  /**
   * GET /api/cart?guestCartId=xxx  (for guest)
   */
  getCartQuery: z
    .object({
      guestCartId: z.string().uuid().optional(),
    })
    .strict(),

  params: {
    productId: z.object({
      productId: z.string().uuid("Product ID must be a valid UUID"),
    }),
  },
};

export type AddToCartInput = z.infer<typeof CartValidation.addItem>;
export type UpdateCartQuantityInput = z.infer<
  typeof CartValidation.updateQuantity
>;
export type MergeCartInput = z.infer<typeof CartValidation.mergeCart>;
export type RemoveItemInput = z.infer<typeof CartValidation.removeItem>;
